config/routes.rb
Rails.application.routes.draw do

  resources :pictures

  #, only: [:show,:new,:edit,:update,:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pictures#index'
  # get '/host=dnkmemes.herokuapp.com'
  get 'user_pictures', to: 'pictures#user_pictures'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.order('created_at')
  end

  def user_pictures
    @pictures = Picture.all
  end
  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to user_pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :url, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Dnk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <% form.label :url %>
    <% form.text_field :url, id: :picture_url %>
  </div>

  <div class="actions">
   <a class="waves-effect waves-light btn red"><%= form.submit %></a>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= photo.title %></h4>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col s6">
			<h1>Edit Your Meme</h1>
		</div><br><br>
		<div class="col s6">
			<%= render 'form', picture: @picture %>
		</div>
		<div class="col s12">
			<%= link_to 'Show', @picture, class: "waves-effect waves-light btn" %>
			<%= link_to 'Back', pictures_path, class: "waves-effect waves-light btn" %>
		</div>
	</div>
</div>

app/views/pictures/index.html.erb
<nav>
    <div class="nav-wrapper">
      <ul class="left hide-on-med-and-down">
        <li><%= link_to 'Meme Gallery', user_pictures_path, class: "waves-effect waves-light btn" %></li>
        <li><%= link_to 'New Picture', new_picture_path, class: "waves-effect waves-light btn" %></li>
      </ul>
    </div>
</nav>
      <br>

<div class="row center-align">
  <div class="col s12">
    <h5>All The Memes All The Time</h5>
  </div>
</div>
<div class="container">
  <div class="row section">
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
      </div>
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
      </div>
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
       </div>
       <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
       </div>
  </div>
  <div class="row section">
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
      </div>
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
      </div>
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
       </div>
       <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
       </div>
  </div>
  <div class="row section">
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
      </div>
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
      </div>
      <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
       </div>
       <div class="col s3">
         <span class="responsive-img"><%= image_tag "", class: "responsive-img" %></span>
       </div>
  </div>
</div>

<footer class="page-footer">
      <div class="container">
      </div>
    </div>
</footer>

app/views/pictures/new.html.erb
<div class="row">

  <div class="col s6">
  </div>
  <div class="col s6">
    <h1 class="center-align">Add a New Meme</h1>
    <div class="container">

        <%= form_for @picture do |f| %>
        <%= render '/pictures/errors', object: @picture %>

        <div class="col s12">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="col s12">
          <%= f.label :image %>
          <%= f.file_field :image, class: 'form-control'%>
        </div>
        <div>
      <a class="waves-effect waves-light btn left"><%= f.submit 'upload', class: "form-control" %></a>
      <i class="medium material-icons right"><%= link_to 'home', root_path %></i>
        </div>
          <% end %>
    </div>
  </div>

</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>
<p>
  <%= image_tag @picture.image.url %>
</p>

<%= link_to 'edit', edit_picture_path(@picture), class: "waves-effect waves-light btn" %>
<%= link_to 'home', root_path, class: "waves-effect waves-light btn" %>
<%= link_to 'Meme Gallery', user_pictures_path, class: "waves-effect waves-light btn" %>

app/views/pictures/user_pictures.html.erb
<div class="container">
  <div class="row center">
    <h1>Memes Gallery</h1>
  </div>
</div>

<div class="row fixed">
    <div class="col s4 offset-s4 red accent-3">
      <% @pictures.each do |picture| %>
        <div class="card hoverable">
          <div class="card-image">
            <%= image_tag picture.image.url, class: "responsive-img" %>
            <span class="card-title black-text bold"><%= picture.title %></span>
          </div> <!-- Closing div card-image -->
          <div class="card-content">
            <i class="left-align small material-icons"><%= link_to 'remove_red_eye', picture %></i>
            <i class="left-align small material-icons"><%= link_to 'edit', edit_picture_path(picture) %></i>
            <i class="left-align small material-icons"><%= link_to 'delete', picture, method: :delete, data: { confirm: 'Are you sure?' } %></i>
          <div class="right-align">
            <i class="small material-icons"><%= link_to "home", root_path %></i>
          </div>
          </div>

        </div> <!-- Closing card div -->
      <% end %>
    </div> <!-- Closing col 4 div offset-s4 -->
</div> <!-- Closing row div -->